// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.AutonomousProgram;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainMotorL;
    public static SpeedController driveTrainMotorR;
    public static RobotDrive driveTrainRobotDrive;
    public static Compressor pneumaticsCompressor;
    public static Solenoid pneumaticsSolenoid;
    public static SpeedController lifterLiftMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainMotorL = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "MotorL", (Talon) driveTrainMotorL);
        
        driveTrainMotorR = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "MotorR", (Talon) driveTrainMotorR);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainMotorL, driveTrainMotorR);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        

        pneumaticsCompressor = new Compressor(0);
        
        
        pneumaticsSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "Solenoid", pneumaticsSolenoid);
        
        lifterLiftMotor = new Talon(2);
        LiveWindow.addActuator("Lifter", "LiftMotor", (Talon) lifterLiftMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
